# Generated by Django 4.1.1 on 2022-11-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('city', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('area', models.FloatField()),
                ('bhk', models.IntegerField()),
                ('description', models.TextField()),
                ('img1', models.ImageField(upload_to='pics')),
                ('img2', models.ImageField(upload_to='pics')),
                ('img3', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
