# Generated by Django 4.1.1 on 2022-11-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_housesold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='sold_or_not_sold',
        ),
        migrations.AddField(
            model_name='house',
            name='not_sold',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
