# Generated by Django 4.1.1 on 2022-11-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_house_sold_or_not_sold_house_not_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='not_sold',
            new_name='sold',
        ),
    ]
