# Generated by Django 4.1.1 on 2022-11-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_dealer_id_alter_dealer_dealer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_address',
        ),
        migrations.AddField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, default='xyz', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(max_length=10),
        ),
    ]
